### ISSUE TITLE
Build a Simple Player Based Model

### ISSUE THREAD

**Issue by catullus** [catullus/mm2017#3]
Challenge:

Based on the rotowire player data, can you wrangle the data and make a REALLY simple model to demonstrate how we'll use it to make predictions? 

* [ ] (1) Take two teams worth of player data
* [ ] (2) Merge it with the team identifiers in the `...data2018\Teams.csv` file
    * [ ] (2a) EXPECTED OUTPUT: these data should have the following columns after merging: `playerName`, `TeamID`, `TeamName`, `LastD1Season`, `...playerStats...`
* [ ] (3) Merge results from (2) with `...data2018\RegularSeasonCompactResults.csv`
    * [ ] (3a) EXPECTED OUTPUT: these data should have the following columns after merging: `playerName`, `TeamID`, `TeamName`, `...columns_from_2a...`, `WTeamID`, `LTeamID`, `WScore`, `LScore`, `WLoc`, `Season`, `DayNum`
* [ ] (4) Take the two merged teams (and multiple players) and build a logistic regression 
    * [ ] Model: game_win_loss ~ FGM_mean
    * where `game_win_loss` is either a binary (0,1) of whether that team won or lost OR the point spread
    * `FGM_mean` is the mean of that team's field goals made BEFORE THE GAME (i.e. we don't want to know who won the game based on how many FGM they made in the game...we want to know if their average FGM stat for the season can predict a game outcome)
* [ ] (5) Use the model object in (4) to make a prediction on a new team where the output is the probability of winning from [0, 1]
* [ ] (6) If you can get to step (5), repeat for the entire set of players and teams for 2017/2018 seasons (if the data are available for these two seasons) with more SIMPLE stats first (i.e. focus on including more of the existing columns)
* [ ] (7) If you get to step (6), do the whole process but with calculated efficiency stats

If we can't make a simple model by step (4), these data aren't going to get us very far in making predictions of future games.

**Comment by cflagg** [comment]
Too much work for the time available. Maybe next year.
